/**
 * @opendata-ai/openchart-core type system barrel export.
 *
 * Re-exports all types from the type modules so consumers can import
 * from '@opendata-ai/openchart-core' directly.
 */

// Encoding rules
export type {
  ChannelRule,
  EncodingRule,
  GraphChannelRule,
} from './encoding';
export {
  CHART_ENCODING_RULES,
  GRAPH_ENCODING_RULES,
  MARK_ENCODING_RULES,
} from './encoding';
// Event types (chart interaction callbacks)
export type {
  ChartEventHandlers,
  ChromeKey,
  ElementEdit,
  ElementRef,
  MarkEvent,
} from './events';
export { elementRef } from './events';
// Layout types (engine output)
export type {
  A11yMetadata,
  ArcMark,
  AreaMark,
  AxisLayout,
  AxisTick,
  BarTableCell,
  CategoryTableCell,
  CellStyle,
  ChartLayout,
  CompileOptions,
  CompileTableOptions,
  FlagTableCell,
  GraphEdgeLayout,
  GraphLayout,
  GraphNodeLayout,
  Gridline,
  HeatmapTableCell,
  ImageTableCell,
  LegendEntry,
  LegendLayout,
  LineMark,
  Margins,
  Mark,
  MarkAria,
  MeasureTextFn,
  PaginationState,
  Point,
  PointMark,
  Rect,
  RectMark,
  ResolvedAnimation,
  ResolvedAnnotation,
  ResolvedChrome,
  ResolvedChromeElement,
  ResolvedColumn,
  ResolvedLabel,
  RuleMarkLayout,
  SankeyLayout,
  SankeyLinkMark,
  SankeyNodeMark,
  SortState,
  SparklineData,
  SparklineTableCell,
  TableCell,
  TableCellBase,
  TableLayout,
  TableRow,
  TextMarkLayout,
  TextStyle,
  TextTableCell,
  TickMarkLayout,
  TooltipContent,
  TooltipField,
} from './layout';
// Spec types (user input)
export type {
  AggregateOp,
  AggregateTransform,
  AnimationConfig,
  AnimationEase,
  AnimationPhaseConfig,
  AnimationSpec,
  AnimationStagger,
  Annotation,
  AnnotationAnchor,
  AnnotationOffset,
  AxisConfig,
  BinParams,
  BinTransform,
  CalculateExpression,
  CalculateTransform,
  ChartSpec,
  ChartSpecOverride,
  ChartSpecWithoutData,
  ChartType,
  Chrome,
  ChromeText,
  ChromeTextStyle,
  Condition,
  ConditionalValueDef,
  DarkMode,
  DataRow,
  Encoding,
  EncodingChannel,
  FieldPredicate,
  FieldType,
  FilterPredicate,
  FilterTransform,
  FoldTransform,
  GradientDef,
  GradientStop,
  GraphEdge,
  GraphEncoding,
  GraphEncodingChannel,
  GraphLayoutConfig,
  GraphNode,
  GraphSpec,
  GraphSpecWithoutData,
  LabelConfig,
  LabelDensity,
  LayerSpec,
  LegendConfig,
  LinearGradient,
  LogicalAnd,
  LogicalNot,
  LogicalOr,
  MarkDef,
  MarkType,
  NodeOverride,
  RadialGradient,
  RangeAnnotation,
  RefLineAnnotation,
  ResolveConfig,
  ResolveMode,
  SankeyEncoding,
  SankeyLinkColor,
  SankeyNodeAlign,
  SankeySpec,
  SankeySpecWithoutData,
  ScaleConfig,
  ScaleType,
  SeriesStyle,
  StoredVizSpec,
  TableSpec,
  TableSpecWithoutData,
  TextAnnotation,
  ThemeConfig,
  TimeUnit,
  TimeUnitTransform,
  Transform,
  VizSpec,
} from './spec';
export {
  CHART_TYPES,
  getRepresentativeColor,
  isChartSpec,
  isConditionalDef,
  isEncodingChannel,
  isGradientDef,
  isGraphSpec,
  isLayerSpec,
  isRangeAnnotation,
  isRefLineAnnotation,
  isSankeySpec,
  isTableSpec,
  isTextAnnotation,
  MARK_DISPLAY_NAMES,
  MARK_TYPES,
  resolveMarkDef,
  resolveMarkType,
} from './spec';
// Table types
export type {
  BarColumnConfig,
  CategoryColorsConfig,
  ColumnConfig,
  HeatmapColumnConfig,
  ImageColumnConfig,
  SparklineColumnConfig,
} from './table';
// Theme types
export type {
  ChromeDefaults,
  ResolvedTheme,
  Theme,
  ThemeChromeDefaults,
  ThemeColors,
  ThemeFontSizes,
  ThemeFonts,
  ThemeFontWeights,
  ThemeSpacing,
} from './theme';
