/**
 * @opendata-ai/openchart-core type system barrel export.
 *
 * Re-exports all types from the type modules so consumers can import
 * from '@opendata-ai/openchart-core' directly.
 */

// Encoding rules
export type {
  ChannelRule,
  EncodingRule,
  GraphChannelRule,
} from './encoding';
export {
  CHART_ENCODING_RULES,
  GRAPH_ENCODING_RULES,
  MARK_ENCODING_RULES,
} from './encoding';
// Event types (chart interaction callbacks)
export type {
  ChartEventHandlers,
  ChromeKey,
  ElementEdit,
  ElementRef,
  MarkEvent,
} from './events';
export { elementRef } from './events';
// Layout types (engine output)
export type {
  A11yMetadata,
  AnnotationFootnote,
  ArcMark,
  AreaMark,
  AxisLayout,
  AxisTick,
  BarListLayout,
  BarListRowMark,
  BarTableCell,
  BaseLegendLayout,
  CategoricalLegendLayout,
  CategoryTableCell,
  CellStyle,
  ChartLayout,
  CompileOptions,
  CompileTableOptions,
  ContinuousLegendBin,
  ContinuousLegendLayout,
  ContinuousLegendTick,
  EndpointLabelEntry,
  EndpointLabelsLayout,
  FacetLayout,
  FacetPanelLayout,
  FillPatternType,
  FlagTableCell,
  GradientColorStop,
  GradientLegendLayout,
  GraphEdgeLayout,
  GraphLayout,
  GraphNodeLayout,
  Gridline,
  HeatmapTableCell,
  ImageTableCell,
  LegendEntry,
  LegendEntryPosition,
  LegendLayout,
  LineMark,
  Margins,
  Mark,
  MarkAria,
  MeasureTextFn,
  PaginationState,
  Point,
  PointMark,
  Rect,
  RectMark,
  ResolvedAnimation,
  ResolvedAnimationPhase,
  ResolvedAnnotation,
  ResolvedChrome,
  ResolvedChromeElement,
  ResolvedColumn,
  ResolvedFillPattern,
  ResolvedLabel,
  ResolvedMetricBar,
  ResolvedMetricCell,
  RuleMarkLayout,
  SankeyLayout,
  SankeyLinkMark,
  SankeyNodeMark,
  SortState,
  SparklineData,
  SparklineTableCell,
  TableCell,
  TableCellBase,
  TableLayout,
  TableRow,
  TextMarkLayout,
  TextStyle,
  TextTableCell,
  TickMarkLayout,
  TileMapLayout,
  TileMapTileMark,
  TooltipContent,
  TooltipField,
} from './layout';
// Spec types (user input)
export type {
  A11yConfig,
  AggregateOp,
  AggregateTransform,
  AnimationConfig,
  AnimationEase,
  AnimationPhaseConfig,
  AnimationSpec,
  AnimationStagger,
  Annotation,
  AnnotationAnchor,
  AnnotationOffset,
  ArcEncoding,
  AreaEncoding,
  AxisConfig,
  BarEncoding,
  BarListEncoding,
  BarListSpec,
  BarListSpecWithoutData,
  BeeswarmEncoding,
  BinParams,
  BinTransform,
  CalculateExpression,
  CalculateTransform,
  ChartSpec,
  ChartSpecOverride,
  ChartSpecWithoutData,
  ChartType,
  Chrome,
  ChromeText,
  ChromeTextStyle,
  ChromeThemeOverride,
  CircleEncoding,
  Condition,
  ConditionalValueDef,
  ConnectorConfig,
  ConnectorType,
  DarkMode,
  DataRow,
  Display,
  Encoding,
  EncodingChannel,
  EndpointLabelsConfig,
  FacetChannel,
  FieldPredicate,
  FieldType,
  FilterPredicate,
  FilterTransform,
  FoldTransform,
  GradientDef,
  GradientStop,
  GraphEdge,
  GraphEncoding,
  GraphEncodingChannel,
  GraphLayoutConfig,
  GraphNode,
  GraphSpec,
  GraphSpecWithoutData,
  LabelConfig,
  LabelDensity,
  LabelSpec,
  LayerSpec,
  LegendConfig,
  LinearGradient,
  LineEncoding,
  LogicalAnd,
  LogicalNot,
  LogicalOr,
  LollipopEncoding,
  MarkDef,
  MarkType,
  Metric,
  NodeOverride,
  PointEncoding,
  RadialGradient,
  RangeAnnotation,
  RangeEncoding,
  RectEncoding,
  RefLineAnnotation,
  RelativeTimeRef,
  ResolveConfig,
  ResolveMode,
  ResponsiveConfig,
  SankeyEncoding,
  SankeyLinkColor,
  SankeyNodeAlign,
  SankeySpec,
  SankeySpecWithoutData,
  ScaleConfig,
  ScaleType,
  SeriesStyle,
  SortByField,
  StoredVizSpec,
  TableSpec,
  TableSpecWithoutData,
  TextAnnotation,
  TextEncoding,
  ThemeConfig,
  TickEncoding,
  TileMapEncoding,
  TileMapPalette,
  TileMapSpec,
  TileMapSpecWithoutData,
  TimeUnit,
  TimeUnitTransform,
  Transform,
  ValueDef,
  VizSpec,
  WindowFieldDef,
  WindowOp,
  WindowSortField,
  WindowTransform,
} from './spec';
export {
  CHART_TYPES,
  getRepresentativeColor,
  isBarListSpec,
  isChartSpec,
  isConditionalDef,
  isEncodingChannel,
  isGradientDef,
  isGraphSpec,
  isLayerSpec,
  isRangeAnnotation,
  isRefLineAnnotation,
  isSankeySpec,
  isTableSpec,
  isTextAnnotation,
  isTileMapSpec,
  isValueDef,
  MARK_DISPLAY_NAMES,
  MARK_TYPES,
  resolveMarkDef,
  resolveMarkType,
} from './spec';
// Table types
export type {
  BarColumnConfig,
  CategoryColorsConfig,
  ColumnConfig,
  HeatmapColumnConfig,
  ImageColumnConfig,
  SparklineColumnConfig,
} from './table';
// Theme types
export type {
  ChromeDefaults,
  ResolvedTheme,
  SeriesStrategy,
  Theme,
  ThemeChromeDefaults,
  ThemeColors,
  ThemeFontSizes,
  ThemeFonts,
  ThemeFontWeights,
  ThemeSpacing,
  TokenValue,
} from './theme';
